/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivitySearchResult: typeof import('./components/ActivitySearchResult.vue')['default']
    ActivitySearchResultBack: typeof import('./components/ActivitySearchResultBack.vue')['default']
    ActivitySearchResultBackTab: typeof import('./components/ActivitySearchResultBackTab.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    CommentSearchResult: typeof import('./components/CommentSearchResult.vue')['default']
    CourseSearchResult: typeof import('./components/CourseSearchResult.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FireClock: typeof import('./components/FireClock.vue')['default']
    FullSearch: typeof import('./components/FullSearch.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    ImportMyTimeTable: typeof import('./components/ImportMyTimeTable.vue')['default']
    ImportPubTimeTable: typeof import('./components/ImportPubTimeTable.vue')['default']
    LocationSearchResult: typeof import('./components/LocationSearchResult.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherSearchResult: typeof import('./components/TeacherSearchResult.vue')['default']
  }
}
